# MongoDB Atlas — acme-cluster
#spring.data.mongodb.uri=mongodb+srv://khengyang88_db_user:V8uW5QL8xFR6rJHm@acme-cluster.xpm0m1u.mongodb.net/acme_fashion?appName=acme-cluster&tlsAllowInvalidCertificates=false&ssl=true
spring.data.mongodb.uri=mongodb+srv://khengyang88_db_user:FIudvB1WZ5tMlXeX@cluster10.yk80ksw.mongodb.net/?appName=Cluster10&tlsAllowInvalidCertificates=false&ssl=true
#spring.data.mongodb.database=acme_fashion
spring.data.mongodb.database=Cluster10

# Server — Cloud Run requires port 8080
server.port=8080

# Allow all hosts — required for Cloud Run
server.tomcat.remoteip.host-header=X-Forwarded-Host
server.forward-headers-strategy=framework

# CORS — allow all origins
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
