# MongoDB Atlas — acme-cluster
spring.data.mongodb.uri=mongodb+srv://khengyang88_db_user:V8uW5QL8xFR6rJHm@acme-cluster.xpm0m1u.mongodb.net/acme_fashion?appName=acme-cluster
#spring.data.mongodb.uri=mongodb+srv://khengyang88_db_user:V8uW5QL8xFR6rJHm@acme-cluster.xpm0mlu.mongodb.net/acme_fashion?appName=acme-cluster
spring.data.mongodb.database=acme_fashion

# Server — Cloud Run requires port 8080
server.port=8080

# Allow requests from the frontend Cloud Run URL
spring.web.cors.allowed-origins=*
